#!/usr/bin/env python

from packetlib.udp_ann_packets import (  # noqa: F401
    ACTION_BYPASS,
    ACTION_OFFLOAD,
    ANN_TASK_MAGIC,
    ANN_UDP_DST_PORT,
    DEFAULT_DST_IP,
    DEFAULT_DST_MAC,
    DEFAULT_DST_PORT_MASK,
    DEFAULT_FEATURE_COUNT,
    DEFAULT_FEATURE_SEED,
    DEFAULT_REQUEST_ID,
    DEFAULT_SRC_IP,
    DEFAULT_SRC_MAC,
    DEFAULT_SRC_PORT,
    DEFAULT_TASK_TYPE,
    OFFLOAD_RESULT_MAGIC,
    IPV4_ETHERTYPE,
    IP_PROTOCOL_TCP,
    IP_PROTOCOL_UDP,
    build_opl_packet,
    build_packet_artifacts,
    build_task_payload,
    build_udp_ann_frame,
    decode_packet_blob,
    parse_feature_values,
    render_opl_words_text,
    rewrite_udp_payload_for_offload,
    task_magic_kind,
)
